version: '3.8'

services:
  mxt:
    build:
      context: '.'
      dockerfile: Dockerfile.local
    restart: always
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    env_file:
      - $PWD/.env
    volumes:
      - $PWD:/go/src
    command: go run cmd/main.go

  mongodb-primary:
    extends:
      file: docker-compose.mongo-replica.yml
      service: mongodb-primary

  mongodb-secondary:
    extends:
      file: docker-compose.mongo-replica.yml
      service: mongodb-secondary

  mongodb-arbiter:
    extends:
      file: docker-compose.mongo-replica.yml
      service: mongodb-arbiter
