{{- range $i, $collection := .Values.targetMongoDBCollections -}}
  {{- if ne $i 0 }}
---
  {{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ "mxt-for" }}-{{ $collection | lower | kebabcase }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
spec:
  serviceName: {{ $.Chart.Name }}
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
        - name: {{ "mxt-for" }}-{{ $collection | lower | kebabcase }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          env:
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: MONGODB_HOST
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: MONGODB_DATABASE_{{ $collection }}
            - name: MONGODB_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: MONGODB_COLLECTION_{{ $collection }}
#            # Optional
#            - name: BIGQUERY_DATASET
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: BIGQUERY_DATASET_{{ $collection }}
#            # Optional
#            - name: BIGQUERY_TABLE
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: BIGQUERY_TABLE_{{ $collection }}
#            # Optional
#            - name: PUBSUB_TOPIC_NAME
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: PUBSUB_TOPIC_NAME{{ $collection }}
#            # Optional
#            - name: PUBSUB_ORDERING_BY
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: PUBSUB_ORDERING_BY{{ $collection }}
            - name: RESUME_TOKEN_VOLUME_DIR
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: RESUME_TOKEN_VOLUME_DIR
#            # Optional
#            - name: FILE_EXPORTER_WRITER
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: FILE_EXPORTER_WRITER
#            # Optional
#            - name: FILE_EXPORTER_WRITER_MAX_MEGABYTES
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: FILE_EXPORTER_WRITER_MAX_MEGABYTES
#            # Optional
#            - name: FILE_EXPORTER_WRITER_MAX_DAYS
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: FILE_EXPORTER_WRITER_MAX_DAYS
#            # Optional
#            - name: FILE_EXPORTER_WRITER_MAX_BACKUPS
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: FILE_EXPORTER_WRITER_MAX_BACKUPS
#            # Optional
#            - name: FILE_EXPORTER_LOG_TYPE_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: FILE_EXPORTER_LOG_TYPE_KEY
#            # Optional
#            - name: FILE_EXPORTER_CHANGE_STREAM_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: FILE_EXPORTER_CHANGE_STREAM_KEY
#            # Optional
#            - name: FILE_EXPORTER_TIME_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: FILE_EXPORTER_TIME_KEY
#            # Optional
#            - name: FILE_EXPORTER_NAME_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: FILE_EXPORTER_NAME_KEY
#            # Optional
#            - name: RESUME_TOKEN_VOLUME_TYPE
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: RESUME_TOKEN_VOLUME_TYPE
#            # Optional
#            - name: RESUME_TOKEN_VOLUME_BUCKET_NAME
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: RESUME_TOKEN_VOLUME_BUCKET_NAME
#            # Optional
#            - name: RESUME_TOKEN_FILE_NAME
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: RESUME_TOKEN_FILE_NAME
#            # Optional
#            - name: RESUME_TOKEN_BUCKET_REGION
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: RESUME_TOKEN_BUCKET_REGION
#            # Optional
#            - name: RESUME_TOKEN_SAVE_INTERVAL_SEC
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: RESUME_TOKEN_SAVE_INTERVAL_SEC
            - name: PROJECT_NAME_TO_EXPORT_CHANGE_STREAMS
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: PROJECT_NAME_TO_EXPORT_CHANGE_STREAMS
            - name: EXPORT_DESTINATION
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: EXPORT_DESTINATION
            - name: TIME_ZONE
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: TIME_ZONE
#            # Optional
#            - name: LOG_LEVEL
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: LOG_LEVEL
#            # Optional
#            - name: LOG_FORMAT
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: LOG_FORMAT
#            # Optional
#            - name: LOG_OUTPUT_DIRECTORY
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: LOG_OUTPUT_DIRECTORY
#            # Optional
#            - name: LOG_OUTPUT_FILE
#              valueFrom:
#                secretKeyRef:
#                  name: {{ $.Values.secrets.name }}
#                  key: LOG_OUTPUT_FILE
          resources: {{ toYaml $.Values.resources | indent 12 }}
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            exec:
              command:
                # cobraを使って作成したコマンド
                - "/go/bin/health"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold : 1
            failureThreshold : 1
          volumeMounts:
            - name: {{ $.Values.containers.volumeMounts.name }}
              mountPath: {{ $.Values.containers.volumeMounts.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ $.Values.containers.volumeMounts.name }}
      spec:
        accessModes: {{ $.Values.volume.accessModes }}
        resources:
          requests:
            storage: {{ $.Values.volume.storage }}
{{- end -}}