package constant

const (
	BIGQUERY_DATASET = "BIGQUERY_DATASET"
	BIGQUERY_TABLE   = "BIGQUERY_TABLE"

	KINESIS_STREAM_NAME   = "KINESIS_STREAM_NAME"
	KINESIS_STREAM_REGION = "KINESIS_STREAM_REGION"

	PUBSUB_TOPIC_NAME = "PUBSUB_TOPIC_NAME"

	MONGODB_HOST                                       = "MONGODB_HOST"
	MONGODB_DATABASE                                   = "MONGODB_DATABASE"
	MONGODB_COLLECTION                                 = "MONGODB_COLLECTION"
	MONGO_WATCH_PIPELINE_EXCLUDE_CS_FULLDOCUMENT_FIELD = "MONGO_WATCH_PIPELINE_EXCLUDE_CS_FULLDOCUMENT_FIELD"

	RESUME_TOKEN_VOLUME_DIR         = "RESUME_TOKEN_VOLUME_DIR"
	RESUME_TOKEN_VOLUME_TYPE        = "RESUME_TOKEN_VOLUME_TYPE"
	RESUME_TOKEN_VOLUME_BUCKET_NAME = "RESUME_TOKEN_VOLUME_BUCKET_NAME"
	RESUME_TOKEN_FILE_NAME          = "RESUME_TOKEN_FILE_NAME"
	RESUME_TOKEN_BUCKET_REGION      = "RESUME_TOKEN_BUCKET_REGION"
	RESUME_TOKEN_SAVE_INTERVAL_SEC  = "RESUME_TOKEN_SAVE_INTERVAL_SEC"

	EXPORT_DESTINATION                    = "EXPORT_DESTINATION"
	PROJECT_NAME_TO_EXPORT_CHANGE_STREAMS = "PROJECT_NAME_TO_EXPORT_CHANGE_STREAMS"

	TIME_ZONE = "TIME_ZONE"

	LOG_LEVEL            = "LOG_LEVEL"
	LOG_FORMAT           = "LOG_FORMAT"
	LOG_OUTPUT_DIRECTORY = "LOG_OUTPUT_DIRECTORY"
	LOG_OUTPUT_FILE      = "LOG_OUTPUT_FILE"

	FILE_EXPORTER_WRITER               = "FILE_EXPORTER_WRITER"
	FILE_EXPORTER_WRITER_MAX_MEGABYTES = "FILE_EXPORTER_WRITER_MAX_MEGABYTES"
	FILE_EXPORTER_WRITER_MAX_DAYS      = "FILE_EXPORTER_WRITER_MAX_DAYS"
	FILE_EXPORTER_WRITER_MAX_BACKUPS   = "FILE_EXPORTER_WRITER_MAX_BACKUPS"
	FILE_EXPORTER_LOG_TYPE             = "FILE_EXPORTER_LOG_TYPE"
	FILE_EXPORTER_CHANGE_STREAM_KEY    = "FILE_EXPORTER_CHANGE_STREAM_KEY"
	FILE_EXPORTER_TIME_KEY             = "FILE_EXPORTER_TIME_KEY"
	FILE_EXPORTER_NAME_KEY             = "FILE_EXPORTER_NAME_KEY"
)
